<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <SailwindDir Condition="'$(SailwindDir)' == ''"
      >$(HOME)/.local/share/Steam/steamapps/common/Sailwind</SailwindDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailGeometry.cs"
      Link="FishermansFlyingSailGeometry.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailOrderText.cs"
      Link="FishermansFlyingSailOrderText.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailFrameGeometry.cs"
      Link="FishermansFlyingSailFrameGeometry.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailTravel.cs"
      Link="FishermansFlyingSailTravel.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailMastInstallationGeometry.cs"
      Link="FishermansFlyingSailMastInstallationGeometry.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailBillow.cs"
      Link="FishermansFlyingSailBillow.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailTension.cs"
      Link="FishermansFlyingSailTension.cs"
    />
    <Compile
      Include="../../Sails/FishermansFlyingSail/FishermansFlyingSailAerodynamics.cs"
      Link="FishermansFlyingSailAerodynamics.cs"
    />
    <Compile Include="../../BoatRigs/*.cs" Link="BoatRigs/%(Filename)%(Extension)" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SailwindDir)/Sailwind_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(SailwindDir)/Sailwind_Data/Managed/UnityEngine.ClothModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
