<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <SailwindDir Condition="'$(SailwindDir)' == ''"
      >$(HOME)/.local/share/Steam/steamapps/common/Sailwind</SailwindDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../PrototypeGeometry.cs" Link="PrototypeGeometry.cs" />
    <Compile Include="../../StayGeometry.cs" Link="StayGeometry.cs" />
    <Compile
      Include="../../BoatRigs/*.cs"
      Exclude="../../BoatRigs/ResolvedRig.cs"
      Link="BoatRigs/%(Filename)%(Extension)"
    />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SailwindDir)/Sailwind_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(SailwindDir)/Sailwind_Data/Managed/UnityEngine.ClothModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
